CREATE DATABASE IF NOT EXISTS usuarios;
CREATE DATABASE IF NOT EXISTS reserva;
CREATE DATABASE IF NOT EXISTS pedido;
CREATE DATABASE IF NOT EXISTS pagos;
CREATE DATABASE IF NOT EXISTS menu;
CREATE DATABASE IF NOT EXISTS inventario;
CREATE DATABASE IF NOT EXISTS cocina;
